// <auto-generated />
namespace RealEstate.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class new_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202502112107426_new_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
