// <auto-generated />
namespace RealEstate.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _2_tablo_eklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_tablo_eklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202501191800369_2_tablo_eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
