// <auto-generated />
namespace RealEstate.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class güncelleme3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(güncelleme3));
        
        string IMigrationMetadata.Id
        {
            get { return "202501281117530_güncelleme3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
