// <auto-generated />
namespace RealEstate.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class güncelleme1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(güncelleme1));
        
        string IMigrationMetadata.Id
        {
            get { return "202501191820407_güncelleme1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
