// <auto-generated />
namespace RealEstate.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class yeni_tablo_TBL_TYPE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yeni_tablo_TBL_TYPE));
        
        string IMigrationMetadata.Id
        {
            get { return "202501151444367_yeni_tablo_TBL_TYPE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
